### PR TITLE
Import more than three highlights per raindrop

### LINKED ISSUE #9: Maxiumum of three highlights/annotations per raindrop get synced to logseq
**Steps to reproduce**
1. Search for a raindrop of which you know that it has more than three highlights
2. Click it in order to add it to logseq

**Expected Outcome**
New page is created with all highlights that are in raindrop

**Actual Outcome**
A maximum of three highlights are created

I could not find any documentation for this, but it seems that when requesting multiple raindrops via `﻿﻿https://api.raindrop.io/rest/v1/raindrops/{collectionId}` a maximum of three highlights are returned. This matches the view in the list views within raindrop, where also only three highlights are shown:
Screenshot 2022-08-21 at 11 55 41
Both  raindrops with highlights in the above screenshot have more than three highlights (as can be seen in the lower right corner, sorry my screenshot annotation tool seems to be currently broken), but only three are shown in the preview. It might be hardcoded in Raindrop API, I could not find any information on this.

A workable solution might be to request the full raindrop via `https://api.raindrop.io/rest/v1/raindrop/{id}` when the user clicks the raindrop and `upsertRaindropPage` is called.

### PR DESCRIPTION
**Pull request by luhmann**
The plugins loads all the highlights that are supposed to be loaded via
the multiple endpoint (ref: https://developer.raindrop.io/v1/raindrops/multiple).
While the documentation is silent about it the response seems to return
a maximum of three highlights per raindrop. This conforms to the number
of highlights shown as preview within the raindrop app.

This adds a call to the endpoint for selecting a single raindrop (ref: https://developer.raindrop.io/v1/raindrops/single)
which again is the same as what the raindrop app itself does to display
all highlights in the footer of a loaded raindrop.

Fix #9

### CODE REVIEW

File: src/util/raindropTransformer.ts [hunk 1]
```diff
@@ -70,10 +70,7 @@ type RaindropResponse = {
 };
 
 // below are normalized values
-export const raindropTransformer = (
-  r: RaindropResponse,
-  collections: Collection[]
```
Comment (luhmann) [inline src/util/raindropTransformer.ts:75]: `collections` was unused, removed it to not need to pass something when transforming the api-response. Might not be the best solution, depending on what you originally intended to do with the parameter

Comment (phildenhoff) [reply src/util/raindropTransformer.ts:75]: No downsides in removing it — if we want it later, we can add it back in. It's a good reminder to set up some better linting for catching unused values

File: src/util/upsertRaindropPage.ts [hunk 2]
```diff
@@ -142,10 +143,48 @@ const upsertAnnotationBlocks = async (
...
 export const upsertRaindropPage = async (r: Raindrop) => {
-  await ioCreateOrLoadPage(r);
-  const pageBlocks = await logseq.Editor.getCurrentPageBlocksTree();
-  const currentPage = await logseq.Editor.getCurrentPage();
-  await ioAddOrRemoveEmptyState(r, pageBlocks, currentPage as PageEntity);
-  await upsertAnnotationBlocks(r, currentPage as PageEntity);
+  const maybeRaindrop = await getSingleRaindrop(r.id);
+
+  if (maybeRaindrop.isJust) {
+    const fullRaindrop = maybeRaindrop.value;
```
Comment (phildenhoff) [inline src/util/upsertRaindropPage.ts:174]: Nice, thanks for using `just` here!

**Review by phildenhoff — APPROVED** [review]
Gave it a quick test and it does work as advertised. Thanks for your (second!!) PR!

**Comment by DonaldoSoWell** [comment]
@luhmann great job thanks ! @phildenhoff Could you please build a release with

**Comment by phildenhoff** [comment]
@DonaldoSoWell now available in v0.0.4! thanks for the reminder
